package worker

import (
	"fmt"
	"math/rand"
	"strings"
	"time"
)

// Processor simulates LLM processing with random delays
type Processor struct {
	minDelay time.Duration
	maxDelay time.Duration
}

func NewProcessor(minDelay, maxDelay time.Duration) *Processor {
	return &Processor{
		minDelay: minDelay,
		maxDelay: maxDelay,
	}
}

// Process simulates LLM inference with a random delay
func (p *Processor) Process(model string, messages []Message) (string, int) {
	// Simulate processing time (200ms to 3s)
	delay := p.minDelay + time.Duration(rand.Int63n(int64(p.maxDelay-p.minDelay)))
	time.Sleep(delay)

	// Extract the last user message
	var userMessage string
	for i := len(messages) - 1; i >= 0; i-- {
		if messages[i].Role == "user" {
			userMessage = messages[i].Content
			break
		}
	}

	promptTokens := len(userMessage) / 4

	// Generate a mock response
	response := generateMockResponse(userMessage, model)

	return response, promptTokens
}

func generateMockResponse(prompt, model string) string {
	responses := []string{
		fmt.Sprintf("This is a simulated response from %s. Your prompt was processed successfully. The key topics identified include: %s",
			model, extractTopics(prompt)),
		fmt.Sprintf("Based on your query, here's what I found: The analysis of '%s' suggests multiple perspectives that could be explored. This response was generated by the mock LLM worker simulating %s.",
			truncate(prompt, 50), model),
		fmt.Sprintf("Thank you for your question. As a mock %s endpoint, I'm providing this simulated response. In a production environment, this would be replaced with actual LLM inference. Your prompt contained approximately %d characters.",
			model, len(prompt)),
		fmt.Sprintf("Processing complete. Model: %s. The mock worker has analyzed your input and generated this response. Key considerations for your prompt include context, specificity, and intended use case.",
			model),
	}

	return responses[rand.Intn(len(responses))]
}

func extractTopics(s string) string {
	words := strings.Fields(s)
	if len(words) > 5 {
		words = words[:5]
	}
	return strings.Join(words, ", ")
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}